management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.security.enabled=false
spring.security.ignored=/actuator/**
