apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: yosratig/webgoat:latest
        ports:
        - containerPort: 8080
        env:
        - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS
          value: "unrestricted"
        - name: MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED
          value: "true"
        volumeMounts:
        - name: props
          mountPath: /home/webgoat/config
      volumes:
      - name: props
        configMap:
          name: webgoat-props
          items:
          - key: application.properties
            path: application.properties
