apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat-ingress
spec:
  tls:
  - hosts:
    - webgoat.local
    secretName: webgoat-tls
  rules:
  - host: webgoat.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webgoat-service
            port:
              number: 8080
