apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /WebGoat
spec:
  tls:
  - hosts:
    - webgoat.local
    secretName: webgoat-tls
  rules:
  - host: webgoat.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webgoat-service
            port:
              number: 8080
